import java.io.*;
import java.util.*;

public class JackSparrow {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int acount= scanner.nextInt();
        int bcount= scanner.nextInt();
        int ccount= scanner.nextInt();
        int dcount= scanner.nextInt();

        int totalWeight = acount+bcount*2+ccount*3+dcount*4;
        
        int boatCount = totalWeight/4
        
}